services:
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.11
    ports:
      - "8080:8080"
    hostname: host.docker.internal
    volumes:
      - ./config-ssl.json:/app/config.json:Z
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8080
      JSON_CONFIG_PATH: /app/config.json
